@startuml

(EZShop)
:Worker:
:Cashier:
:WarehouseWorker:
:Owner:
:Customer:
:AnonymousCustomer:
:CashRegister:
:FidelityCard:
:POS:
:Product:

Worker<|--Cashier
Worker<|--WarehouseWorker
Worker<|--Owner

Customer--|>AnonymousCustomer

(EZShop)<--Worker
(EZShop)<--AnonymousCustomer
(EZShop)<--CashRegister
(EZShop)<--FidelityCard
(EZShop)<--POS
(EZShop)<--Product

@enduml