@startuml
(EZShop)
:Worker:
:Cashier:
:WarehouseWorker:
:Maintainer:
:Owner:
:Manager:
:Customer:
:Subscriber:
:AnonymousCustomer:
:Device:

Worker<|--Cashier
Worker<|--WarehouseWorker
Worker<|--Maintainer
Worker<|--Owner
Worker<|--Manager

Customer<|--Subscriber
Customer<|--AnonymousCustomer

(EZShop)<--Worker
(EZShop)<--Customer
(EZShop)<--Device

@enduml