@startgantt
Project starts the 5th of april 2021
2021-04-05 to 2021-04-21 are named [Requirements planning]
2021-04-05 to 2021-04-21 are colored in salmon 
2021-04-21 to 2021-04-30 are named [Design]
2021-04-21 to 2021-04-30 are colored in Lavender
2021-04-30 to 2021-05-19 are named [Coding]
2021-04-30 to 2021-05-19 are colored in #AAF

[Perform work analysis] lasts 1 days
[Model process] lasts 1 days
[Identify stakeholders] lasts 1 days
[Identify context and interfaces] lasts 1 days
[Analize stories and personas] lasts 1 days
[Identify user requirements] lasts 1 days
[Identify non functional requirements] lasts 1 days
[Identify use cases] lasts 1 days
[Define important terms] lasts 1 days
[Define system design] lasts 1 days
[Define deployment] lasts 1 days
[Create requirements document] lasts 14 days
[Create a GUI prototype] lasts 2 days
[Define high level] lasts 2 days
[Define low level design] lasts 2 days
[Verification traceability matrix] lasts 2 days
[Verification sequence diagrams] lasts 2 days
[Identify algorithm for methods class] lasts 2 days
[Write the code] lasts 2 days
[Integration GUI with code] lasts 2 days
[Identify test cases] lasts 2 days
[Analize test] lasts 2 days

[Model process] starts at [Perform work analysis]'s end
[Identify stakeholders] starts at [Model process]'s end
[Identify context and interfaces] starts at [Identify stakeholders]'s end
[Analize stories and personas] starts at [Identify context and interfaces]'s end
[Identify user requirements] starts at [Analize stories and personas]'s end
[Identify non functional requirements] starts at [Analize stories and personas]'s end
[Identify use cases] starts at [Identify non functional requirements]'s end
[Define important terms] starts at [Identify use cases]'s end
[Define system design] starts at [Define important terms]'s end
[Define deployment] starts at [Define system design]'s end
[Create requirements document] starts at [Model process]'s end
[Create a GUI prototype] starts at [Create requirements document]'s end
[Define high level] starts at [Create a GUI prototype]'s end
[Define low level design] starts at [Define high level]'s end
[Verification traceability matrix] starts at [Define low level design]'s end
[Verification sequence diagrams] starts at [Verification traceability matrix]'s end
[Identify algorithm for methods class] starts at [Verification sequence diagrams]'s end
[Write the code] starts at [Identify algorithm for methods class]'s end
[Integration GUI with code] starts at [Write the code]'s end
[Identify test cases] starts at [Integration GUI with code]'s end
[Analize test] starts at [Identify test cases]'s end
@endgantt