@startuml
class order {
    int orderNumber
}

class supplier {
}

class catalogue {
}

class shop {
}

class Person {
    String name
    String surname
    int age
    String accountName
    String email
}

class owner {
}

class "Warehouse Worker" {
}

class cashier {
}

class customer {
}

class Product {
    String barCode
    int numberOfProducts
}

class "Product descriptor" {
    int ID
    String ProductAttribute
}

class "cash register" {
    int maxAmount
}

class inventory {
    int numberOfObjects
}

class transaction {
    int transactionNumber
    float amount
}

class "credit card" {
    int creditCardNumber
    int creditCardType
}

class cash {
    string currency
}

class "fidelity card" {
    int fideltyCardNumber
    string barCode
}

class POS {
}

shop --- inventory
shop --- catalogue
shop --- "*" order : issues
shop ---- "*" transaction : "manages"
shop ---up owner : manages 



catalogue -- "*" "Product descriptor" : contains

order "*" -- supplier
order -- "*" "Product descriptor"

Person <|-- owner
Person <|-- cashier
Person <|- "Warehouse Worker"
Person <|-- customer


customer --- "0..1" "fidelity card"
customer --- cash
customer --- "0..*" "credit card"

transaction ---up "0..1" cash
transaction "*" ---up "0..1" "credit card"
transaction "*" ---up "0..1" "fidelity card"

cash "*" --- "cash register" : contains

Product "*" ---up "Product descriptor" : is described by >
Product ---up transaction
Product "*" ---up inventory

"cash register" ---- cashier : < interacts with
"fidelity card" --- cashier : < manages

"Warehouse Worker" "*" -- "*" inventory

POS --up cashier : < interacts with
POS "0..1" --left "*" "credit card"
POS "0..1" --up "*" transaction 
@enduml