@startuml
class order {
    int oderdNumeber
}

class supplier {
}

class catalogue {
}

class shop {
}

class user {
    String name
    String surname
    String age
    String accountName
    String email
}

class owner {
}

class employee {
}

class cashier {
}

class customer {
    int fidelityCardAssociated
}

class item {
    
}

class "item descriptor" {
}

class "cash register" {
    int maxAmount
}

class sale {
}

class inventory {
    int numberOfObjects
}

class transaction {
    int transactionNumber
    float amount
}

class "credit card" {
    int creditCardNumber
    int creditCardType
}

class cash {
    string currency
}

class "fidelity card" {
    int fideltyCardNumber
    string barCode
}

shop -- inventory
shop -- catalogue
shop -- "*" order : issues
shop -- "*" transaction : "manages"

transaction <|-- sale

catalogue -- "*" "item descriptor" : contains

order "*" -- supplier
order -- "*" "item descriptor"

user <|-- owner
user <|-- cashier
user <|-- employee
user <|-- customer


user -- "0..*" "fidelity card"
user --up cash
user -- "0..*" "credit card"

transaction -- "0..1" cash
transaction "*" -- "0..1" "credit card"

cash "*" --right "cash register" : contains

item -- "item descriptor" : is described by >
@enduml