@startuml

:Worker:
:Cashier:
:WarehouseWorker:
:Owner:
:Customer:
:AnonymousCustomer:
:POS:
:CashRegister:

Worker<|--Cashier
Worker<|--WarehouseWorker
Worker<|--Owner

AnonymousCustomer<|--Customer
(EZShop)
(EZShop)
(Autorization and authentication)
(Manage workers)
(Manage customers)
(Manage inventory)
(Manage sales)
(Support accounting)

(EZShop)-up..>(Autorization and authentication) : <<include>>
(EZShop)-up.>(Manage workers) : <<include>>
(EZShop)-up.>(Manage customers) : <<include>>
(EZShop)-up.>(Manage inventory) : <<include>>
(EZShop)-up.>(Manage sales) : <<include>>
(EZShop)-up.>(Support accounting) : <<include>>

:Worker: --> (Autorization and authentication)

:Owner:-->(Manage workers)

:Cashier:-->(Manage customers)
(Manage customers)<--:Customer:
(Manage sales)<--:AnonymousCustomer:


:WarehouseWorker:-->(Manage inventory)

:Cashier:-->(Manage sales)

:Owner:-->(Support accounting)

:POS:-->(Manage sales)

:CashRegister:-->(Manage sales)

@enduml